import { useState } from 'react'
import { ArrowRight, Camera, Check, ChevronDown, CircleArrowRight, ClipboardList, Hammer, Home, Mail, MapPin, Menu, Phone, Ruler, Sparkles, X } from 'lucide-react'
import './App.css'

type ProjectCategory = 'All' | 'Renovations' | 'Kitchens' | 'Bathrooms' | 'Interiors' | 'Exteriors'
type Project = { title: string; category: Exclude<ProjectCategory, 'All'>; image: string; size: string; detail: string }

const projects: Project[] = [
  { title: 'Warm modern living', category: 'Interiors', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85', size: 'project-large', detail: 'A calm, considered interior concept with natural textures and an easy sense of flow.' },
  { title: 'The kitchen, reworked', category: 'Kitchens', image: 'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1000&q=85', size: 'project-tall', detail: 'A bright kitchen direction built around thoughtful storage, durable surfaces, and everyday use.' },
  { title: 'A quieter bathroom', category: 'Bathrooms', image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1000&q=85', size: 'project-short', detail: 'A refined bathroom palette that makes room for both function and a little restoration.' },
  { title: 'Ottawa exterior study', category: 'Exteriors', image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85', size: 'project-short', detail: 'A welcoming exterior concept focused on proportion, materiality, and lasting curb appeal.' },
  { title: 'Open-plan living', category: 'Renovations', image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85', size: 'project-tall', detail: 'An adaptable renovation approach that brings light and clarity to the heart of the home.' },
  { title: 'Materials in conversation', category: 'Interiors', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=85', size: 'project-large', detail: 'A material-led interior direction pairing warm timber, quiet stone, and precise details.' },
]

const services = [
  { icon: Home, label: 'Home renovations', text: 'Thoughtful improvements that help your home work better and feel more like you.' },
  { icon: Sparkles, label: 'Kitchens & bathrooms', text: 'Well-considered spaces shaped around daily rituals, practical details, and enduring style.' },
  { icon: Ruler, label: 'Interior improvements', text: 'From layout updates to finish selections, we bring clarity to the spaces between.' },
  { icon: Hammer, label: 'Exterior improvements', text: 'A considered approach to the outside of your home, from first impression to final detail.' },
  { icon: ClipboardList, label: 'General contracting', text: 'A clear, organized project experience for work that needs capable coordination.' },
  { icon: Sparkles, label: 'Custom projects', text: 'Have something specific in mind? Let’s shape the right approach together.' },
]

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [filter, setFilter] = useState<ProjectCategory>('All')
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)
  const [submitted, setSubmitted] = useState(false)
  const filteredProjects = filter === 'All' ? projects : projects.filter((project) => project.category === filter)
  const closeMenu = () => setMenuOpen(false)
  const navItems = ['Home', 'Services', 'About', 'Projects', 'Contact']
  const filters: ProjectCategory[] = ['All', 'Renovations', 'Kitchens', 'Bathrooms', 'Interiors', 'Exteriors']

  return (
    <div className="site-shell">
      <header className="site-header">
        <a className="brand" href="#top" onClick={closeMenu} aria-label="Prestige Contractors Ottawa home"><span className="brand-mark">P</span><span><strong>Prestige Contractors Ottawa</strong></span></a>
        <nav className={menuOpen ? 'main-nav is-open' : 'main-nav'} aria-label="Main navigation">
          {navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={closeMenu}>{item}</a>)}
          <a className="nav-cta" href="#contact" onClick={closeMenu}>Get a Free Quote <ArrowRight size={16} /></a>
        </nav>
        <button className="menu-button" type="button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
      </header>

      <main id="top">
        <section className="hero-section" aria-labelledby="hero-title"><div className="hero-overlay" /><div className="hero-content reveal-up"><p className="eyebrow light">A proposal for Ottawa homeowners</p><h1 id="hero-title">Quality craftsmanship.<br /><em>Built for Ottawa.</em></h1><p className="hero-copy">Professional renovations and construction, shaped around the way you want to live.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Get a Free Quote <ArrowRight size={17} /></a><a className="text-link light-link" href="#projects">View our work <CircleArrowRight size={18} /></a></div></div><div className="hero-note"><span className="line" /><span>Residential & general contracting<br />Ottawa, Ontario</span></div><a className="scroll-cue" href="#services" aria-label="Scroll to services"><span>Scroll to explore</span><ChevronDown size={18} /></a></section>
        <section className="trust-strip" aria-label="Our values"><div><span>01</span><strong>Quality craftsmanship</strong></div><div><span>02</span><strong>Reliable service</strong></div><div><span>03</span><strong>Attention to detail</strong></div><div><span>04</span><strong>Ottawa & surrounding areas</strong></div></section>
        <section className="section services-section" id="services"><div className="section-heading"><div><p className="eyebrow">What we do</p><h2>Considered work.<br /><em>Beautifully finished.</em></h2></div><p className="section-intro">From the first conversation to the final detail, this concept is designed around a clear, thoughtful experience for homeowners.</p></div><div className="services-grid">{services.map(({ icon: Icon, label, text }, index) => <article className="service-card" key={label}><span className="service-number">0{index + 1}</span><Icon className="service-icon" size={26} strokeWidth={1.5} /><h3>{label}</h3><p>{text}</p><a href="#contact" aria-label={`Discuss ${label}`}><ArrowRight size={18} /></a></article>)}</div></section>
        <section className="about-section" id="about"><div className="about-image"><img src="https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=85" alt="Architectural detail of a modern home" /><div className="image-caption">The details make<br /><em>the difference.</em></div></div><div className="about-copy"><p className="eyebrow">About the concept</p><h2>A better standard<br />for <em>building home.</em></h2><p>Prestige Contractors Ottawa is imagined as the kind of local partner homeowners can trust with the important work: a thoughtful approach, honest communication, and a sharp eye for the details that make a space feel right.</p><p>Whether the project is a focused update or a more involved transformation, every decision should feel considered and every step easy to understand.</p><a className="text-link" href="#contact">Start a conversation <ArrowRight size={18} /></a></div></section>
        <section className="section projects-section" id="projects"><div className="section-heading projects-heading"><div><p className="eyebrow">Selected work</p><h2>Spaces with a<br /><em>sense of place.</em></h2></div><p className="section-intro">A placeholder gallery for the work that will define the Prestige Contractors Ottawa story. Real project photography can be added here later.</p></div><div className="filter-row" role="tablist" aria-label="Project categories">{filters.map((category) => <button key={category} className={filter === category ? 'filter-button active' : 'filter-button'} type="button" onClick={() => setFilter(category)} role="tab" aria-selected={filter === category}>{category}</button>)}</div><div className="projects-grid">{filteredProjects.map((project) => <button className={`project-card ${project.size}`} key={project.title} type="button" onClick={() => setSelectedProject(project)}><img src={project.image} alt={project.title} /><span className="project-wash" /><span className="project-meta"><small>{project.category}</small><strong>{project.title}</strong></span><span className="project-arrow"><ArrowRight size={20} /></span></button>)}</div></section>
        <section className="why-section"><div className="why-inner"><div><p className="eyebrow light">Why this approach</p><h2>Good work is<br /><em>felt in the details.</em></h2></div><div className="why-list"><div><Check /><span><strong>Quality-focused workmanship</strong><small>A considered finish from the big decisions to the small ones.</small></span></div><div><Check /><span><strong>Professional communication</strong><small>Clear conversations and an organized project experience.</small></span></div><div><Check /><span><strong>Personalized solutions</strong><small>A plan that responds to your home, your priorities, and your life.</small></span></div></div></div></section>
        <section className="section process-section"><div className="section-heading"><div><p className="eyebrow">The process</p><h2>From first idea<br />to <em>finished result.</em></h2></div><p className="section-intro">A simple, human process that keeps the project moving and the decisions feeling manageable.</p></div><div className="process-grid"><div><span>01</span><h3>Tell us about<br />your project</h3><p>Start with the vision, the wish list, or simply the problem to solve.</p></div><div><span>02</span><h3>Get your<br />quote</h3><p>We’ll talk through the right scope and next steps for your project.</p></div><div><span>03</span><h3>Plan<br />& build</h3><p>With a clear plan in place, the work begins with care and attention.</p></div><div><span>04</span><h3>Enjoy the<br />finished result</h3><p>A home that feels more useful, more personal, and more yours.</p></div></div></section>
        <section className="testimonial-section"><div className="testimonial-mark">“</div><p className="eyebrow">A place for your voice</p><blockquote>“Client testimonial will be added here.”</blockquote><p className="testimonial-note">Demo placeholder · Real customer feedback to be added</p><div className="testimonial-dots"><span className="active" /><span /><span /></div></section>
        <section className="quote-banner"><div><p className="eyebrow light">Let’s talk about what’s next</p><h2>Ready to start your<br /><em>next project?</em></h2></div><a className="button button-light" href="#contact">Request a Free Quote <ArrowRight size={17} /></a></section>
        <section className="contact-section" id="contact"><div className="contact-intro"><p className="eyebrow">Start a conversation</p><h2>Tell us what<br /><em>you’re planning.</em></h2><p>Have a renovation in mind, a project to scope, or simply a few questions? This is the place to begin.</p><div className="contact-details"><div><Phone size={18} /><span><small>Phone</small><strong>To be confirmed</strong></span></div><div><Mail size={18} /><span><small>Email</small><strong>To be confirmed</strong></span></div><div><MapPin size={18} /><span><small>Service area</small><strong>Ottawa & surrounding areas</strong></span></div></div></div><form className="quote-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}>{submitted ? <div className="form-success"><Check size={32} /><h3>Thanks for reaching out.</h3><p>This demo form is ready to connect to the business’s preferred inbox.</p><button type="button" className="text-link" onClick={() => setSubmitted(false)}>Send another message <ArrowRight size={17} /></button></div> : <><div className="form-row"><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label></div><div className="form-row"><label>Phone<input name="phone" placeholder="Your phone number" /></label><label>Project type<select name="projectType" defaultValue=""><option value="" disabled>Select a project type</option><option>Home renovation</option><option>Kitchen or bathroom</option><option>Interior improvements</option><option>Exterior improvements</option><option>Custom project</option></select></label></div><label>Tell us a little about your project<textarea name="message" rows={4} placeholder="What are you thinking about?" /></label><button className="button button-dark" type="submit">Send project enquiry <ArrowRight size={17} /></button><p className="form-note">Demo concept · No information is sent from this form.</p></>}</form></section>
        <section className="map-placeholder"><div className="map-grid" /><div className="map-label"><MapPin size={18} /><span><strong>Ottawa, Ontario</strong><small>Service area visual placeholder</small></span></div><div className="map-pin pin-one" /><div className="map-pin pin-two" /><div className="map-pin pin-three" /></section>
      </main>
      <footer className="site-footer"><div className="footer-top"><a className="brand footer-brand" href="#top"><span className="brand-mark">P</span><span><strong>Prestige Contractors Ottawa</strong></span></a><p>A proposal for a more considered<br />contracting experience in Ottawa.</p><a className="instagram-placeholder" href="#contact"><Camera size={18} /> Instagram <span>coming soon</span></a></div><div className="footer-bottom"><span>© 2026 Prestige Contractors Ottawa · Concept website</span><span>Phone, email & business address to be confirmed</span><a href="#top">Back to top <ArrowRight size={15} /></a></div></footer>
      {selectedProject && <div className="modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><div className="project-modal" role="dialog" aria-modal="true" aria-label={selectedProject.title} onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setSelectedProject(null)} aria-label="Close project details"><X size={20} /></button><img src={selectedProject.image} alt="" /><div><p className="eyebrow">{selectedProject.category}</p><h2>{selectedProject.title}</h2><p>{selectedProject.detail}</p><p className="form-note">Project details and photography to be confirmed with the business owner.</p></div></div></div>}
    </div>
  )
}

export default App
